version: 2
jobs:
  build:
    working_directory: ~/demo_web_app
    parallelism: 1

    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          RACK_ENV: test
          PG_HOST: localhost
          PGUSER: ubuntu
      - image: circleci/postgres:9.4.12-alpine
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: demo_web_app_test

    steps:
      - checkout

     # Restore bundle cache
      - restore_cache:
         keys:
           - demo-web-app-{ checksum "Gemfile.lock" }}
           - demo-web-app- # used if checksum fails

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

     # Store bundle cache
      - save_cache:
         key: demo-web-app-{{ checksum "Gemfile.lock" }}
         paths:
           - vendor/bundle

      # Check code formatting
      - run:
          name: Check code formatting
          command: bundle exec rubocop

      - run:
          name: Migrate DB
          environment:
            RAILS_ENV: test
          command: bundle exec rake db:create db:migrate db:seed --trace

      # Test
      - run:
          name: Run rspec
          command: |
            bundle exec rspec --format RspecJunitFormatter \
                              --out tmp/test-results/rspec.xml \
                              --color \
                              --format Fuubar \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Teardown
      # Save test results
      - store_test_results:
          path: tmp/test-results
