# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Admin User
  admin_email: admin@test.com
  admin_password: 1234567890
  gmail_username: howitzerexample
  gmail_password: strongqa.com
  secret_key_base: dc8307d9530247dbbe625d10696ba6d2193e52779c81ddb0e30cbcaf3ff3aa710d7b380af3befb9a4dc5dfba9ecc61525e0ec38a9be3e3326eebba05544ab30e

test:
  secret_key_base: 9ab516608250895f26d96c01937ae6ba46f99ef2954ae21c5e7fa9b7c14253ee9c93600be9d813359c2b9f57d33fe5fef53d44d39c04915ad5009a62414f63d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  gmail_username: <%= ENV["GMAIL_USERNAME"] %>
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
